### ISSUE TITLE
Not possible to open results file: No such file or directory

### ISSUE THREAD

**Issue by ilyaelizarov** [ghorwin/FMICodeGenerator#37] opened 2021-07-28 16:34 UTC
Hi guys!

I generated an FMU from P_Controller tutorial, and tried to use it in Dymola, but the following error appears:
"Not possible to open file "Unnamed2.mat": No such file or directory".

Unnamed2.mat is an output file for storing simulation results in Dymola.

The log is:
[fmi2OK]: P_Control_fmu: fmi2SetupExperiment: Call of setup experiment.
[fmi2OK]: P_Control_fmu: fmi2EnterInitializationMode: Go into initialization mode.
[fmi2OK]: P_Control_fmu: Starting initialization.
[fmi2OK]: P_Control_fmu: Initialization complete.
[fmi2OK]: P_Control_fmu: fmi2ExitInitializationMode: Go out from initialization mode.
Simulation successfully terminated
Terminate signaled by FMU
Error: Terminate command at starting point.
[fmi2OK]: P_Control_fmu: fmi2Terminate: Terminate model.
[fmi2OK]: P_Control_fmu: fmi2FreeInstance: Model instance deleted.

At the same time, I could run fmuCheck on this FMU without any errors.  It seems that OpenModelica and SimulationX work with this FMU well too.

It seems that only co-simulation works in Dymola. Model exchange fails.

What could it be?

**Comment by ghorwin** [comment] 2021-07-29 07:52
Hi, this is likely a Dymola model-related feature. Custom mat files do not have anything to do with FMUs (unless you try to read this file from within the FMU).
My guess is that the error message by Dymola is rather a warning and is unrelated to the actual FMU termination problem.

The interesting question is: where does the "Terminate signaled by FMU" error comes from? The `P_Control_fmu` appears to run through the initialization successfully (also, fmuCheck runs a full co-simulation, so that shouldn't be an issue). 

From your observation about "co-sim works, model-exchange fails" I'd look at the ModelExchange code in your FMU. Maybe you could share it here and we look at potential out-of-index errors or exceptions.

**Comment by ilyaelizarov** [comment] 2021-07-30 14:13
Hi,

Yes, you're right. The problem that the FMU fails right after the initialization. Dymola is not able to open .mat file since there is no output results in model exchange mode.

Here is my code:
```
// model exchange: implementation of derivative and output update
void P_Control_final::updateIfModified() {
	if (!m_externalInputVarsModified)
		return;

	// get input variables
	double T = m_realVar[FMI_INPUT_T];
	double Tlimit = m_realVar[FMI_PARA_Tlimit];
	double kP = m_realVar[FMI_PARA_kP];


	// TODO : implement your code here
	double P = 0;
	if (T < Tlimit)
		P = kP*(Tlimit - T);

	// output variables
	m_realVar[FMI_OUTPUT_P] = P; // TODO : store your results here


	// reset externalInputVarsModified flag
	m_externalInputVarsModified = false;
}
```
and
```
// Co-simulation: time integration
void P_Control_final::integrateTo(double tCommunicationIntervalEnd) {

	// state of FMU before integration:
	//   m_currentTimePoint = t_IntervalStart;

	// get input variables
	// double T = m_realVar[FMI_INPUT_T];
	// double Tlimit = m_realVar[FMI_PARA_Tlimit];
	// double kP = m_realVar[FMI_PARA_kP];



	// TODO : implement your code here
	updateIfModified();


	// output variables
	//m_realVar[FMI_OUTPUT_P] = 0; // TODO : store your results here


	m_currentTimePoint = tCommunicationIntervalEnd;

	// state of FMU after integration:
	//   m_currentTimePoint = tCommunicationIntervalEnd;
}

```
It is exactly the same as in your tutorial for P_Control.FMU. 

I was able to get some details for debugging if it helps:

> [fmi2OK]: P_Control_final_fmu: fmi2SetupExperiment: Call of setup experiment.
> [fmi2OK]: P_Control_final_fmu: fmi2EnterInitializationMode: Go into initialization mode.
> [fmi2OK]: P_Control_final_fmu: Starting initialization.
> [fmi2OK]: P_Control_final_fmu: Initialization complete.
>   Variable p_Control_final_fmu._first = 0 at time 0
>   Variable p_Control_final_fmu._startValuesNotSet = 0 at time 0
> Expression P_Control_final_fmu.fmi_Functions.CheckIfDiscreteValueSet(
> p_Control_final_fmu.fmi, 
> p_Control_final_fmu.myTime, 
> {const.k}, 
> fill(false, 0), 
> fill(0, 0), 
> {1}, 
> fill(0, 0), 
> fill(0, 0), 
> {p_Control_final_fmu.P}, 
> fill(false, 0), 
> fill(0, 0)) > 0.5 became true ( (P_Control_final_fmu.fmi_Functions.CheckIfDiscreteValueSet(
> p_Control_final_fmu.fmi, 
> p_Control_final_fmu.myTime, 
> {const.k}, 
> fill(false, 0), 
> fill(0, 0), 
> {1}, 
> fill(0, 0), 
> fill(0, 0), 
> {p_Control_final_fmu.P}, 
> fill(false, 0), 
> fill(0, 0)))-(0.5) = 0.5 )
> Expression P_Control_final_fmu.fmi_Functions.fmiCompletedIntegratorStep(
> p_Control_final_fmu.fmi, 
> p_Control_final_fmu.myTime) > 0.5 became false ( (P_Control_final_fmu.fmi_Functions.fmiCompletedIntegratorStep(
> p_Control_final_fmu.fmi, 
> p_Control_final_fmu.myTime))-(0.5) = -0.5 )
> Iterating to find consistent restart conditions.
>   Variable p_Control_final_fmu._first = 0 at time 0
>   Variable p_Control_final_fmu._startValuesNotSet = 0 at time 0
>   Variable p_Control_final_fmu.fmi_flip = 1 at time 0
> [fmi2OK]: P_Control_final_fmu: fmi2ExitInitializationMode: Go out from initialization mode.
> Simulation successfully terminated
> Terminate signaled by FMU
>   Variable p_Control_final_fmu.fmi_flip = 0 at time 0
>   Variable p_Control_final_fmu.fmi_iterationConverged = 1 at time 0
> Error: Terminate command at starting point.
> [fmi2OK]: P_Control_final_fmu: fmi2Terminate: Terminate model.
> [fmi2OK]: P_Control_final_fmu: fmi2FreeInstance: Model instance deleted.

My Dymola version is 2020x (64-bit), 2019-10-10

**Comment by ghorwin** [comment] 2021-08-01 11:27
Ok, from the output of `Integration terminated successfully at T = 1` it looks as if the simulation completed  successfully. So FMU modelExchange seems to work ok.

However, the performance warning indicates that Dymola does a lot of sampling. This has to be resolved by adjusting Dymola simulation/solver parameters. Alas, I cannot help here, since I do not use Dymola myself (maybe ask Dymola support?).

Since the FMU code generated by FMI CodeGenerator seems to work ok, I'm closing the issue.

**Comment by ghorwin** [comment] 2021-08-01 11:31
As for the modelExchange, I have testet the code generator-modelExchange code only with SimulationX, but I'll try to run the FMU through PyFMI. Stay tuned....

**Comment by ghorwin** [comment] 2022-03-29 21:12
No further insight into that matter... closing issue since I cannot reproduce this problem myself and I must assume, this is a Dymola-Issue

**Closed by ghorwin** 2022-03-29 21:12 UTC
